name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check no features
      run: cargo check --verbose --no-default-features
    - name: Check only serde feature
      run: cargo check --verbose --no-default-features --features "serde"
    - name: Check only bytemuck feature
      run: cargo check --verbose --no-default-features --features "bytemuck"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
